//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAsyncExamples.BruteForce.Client.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EngineStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngineStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetAsyncExamples.BruteForce.Client.Core.Resources.EngineStrings", typeof(EngineStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All workers finished..
        /// </summary>
        internal static string MessageAllWorkersFinished {
            get {
                return ResourceManager.GetString("MessageAllWorkersFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0}. Cancellation requested..
        /// </summary>
        internal static string MessageCancellationRequested {
            get {
                return ResourceManager.GetString("MessageCancellationRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0}. Login with password &lt;{1}&gt; failed..
        /// </summary>
        internal static string MessageLoginFailed {
            get {
                return ResourceManager.GetString("MessageLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0}. Login succeeded with password &lt;{1}&gt;. Requesting cancellation for other workers..
        /// </summary>
        internal static string MessageLoginSucceeded {
            get {
                return ResourceManager.GetString("MessageLoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0}. Trying password &lt;{1}&gt;....
        /// </summary>
        internal static string MessageTryingPassword {
            get {
                return ResourceManager.GetString("MessageTryingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0}: Finished with no success..
        /// </summary>
        internal static string MessageWorkerFinished {
            get {
                return ResourceManager.GetString("MessageWorkerFinished", resourceCulture);
            }
        }
    }
}
